version: "3.1"
services:
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "123456789"
            ACCEPT_EULA: "Y"
        ports:
            - "1434:1433"